export const data=
[
	{ 
	"English": "Times",
	"Kannada":"ಸಲ",
	"RomanUrdu":"Martaba",
	"EnglishEvening": "Evening",
	"KannadaEvening":"ಸಂಜೆ",
	"RomanUrduEvening":"Shaam",
	
 	}
	,[
	{
	"Id": 1,
	"ArabicText": "الْحَمْدُ لِلَّهِ وَحْدَهُ وَالصَّلَاةُ وَالسَّلَامُ عَلَى مَنْ لَا نَبِيَّ بَعْدَهُ",
	"EnglishText": "Alhamdulillahi wahdah, wassalaatu wassalaamu a'laa man la nabiyya ba'adah",
	"EnglishTranslate": "All praise is due to Allah alone,and peace and blessings be upon him after whom there is no other Prophet.",
	"RomanUrduText": "Alhamdulillahi wahdah, wassalaatu wassalaamu a'laa man la nabiyya ba'adah.",
	"RomanUrduTranslate":"Saari tareef sirf Allah ke liye hai aur darood o salaam ho us Nabi par jis ke baad koi Nabi nahi.",
	"KannadaText":"ಅಲ್‍ಹಮ್ದುಲಿಲ್ಲಾಹಿ ವಹ್ದಹೂ, ವಸ್ಸಲಾತು ವಸ್ಸಲಾಮು ಅಲಾ ಮನ್ ಲಾ ನಬಿಯ್ಯ ಬಅïದಹು",
	"KannadaTranslate":"ಸರ್ವಸ್ತುತಿಗಳು ಅಲ್ಲಾಹನಿಗೆ ಮೀಸಲು, ಅವನ ಸಲಾತ್ ಮತ್ತು ಸಲಾಮ್ ಯಾರ ಬಳಿಕ ಬೇರೆ ಪ್ರವಾದಿಯಿಲ್ಲವೋ ಅವರ ಮೇಲಿರಲಿ.",
	"Timing":"morningAndEvening",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/75.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "أَعُوذُ بِاللَّهِ مِنَ الشَّيطَانِ الرَّجِيمِ  ۞ اللَّهُ لاَ إِلَهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ لَّهُ مَا فِي السَّمَوَاتِ وَمَا فِي الأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلاَ يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلاَّ بِمَا شَاء وَسِعَ كُرْسِيُّهُ السَّمَوَاتِ وَالْأَرْضَ وَلاَ يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ",
	"EnglishText": "A'oothu billaahi minash-Shaytaanir-rajeem.Allaahu laa ilaaha illa huwal hayyul qayyoom, laa ta'khuzuhu sinatuw  walaa naum, lahu maa fis samaawaati wamaa fil arz, man zallazi yash-fa'ou 'indahu illa bi-iznih, ya'lamu maa baina aideehim wamaa khalfahum, walaa yuhitoona bishae-im min 'ilmihee illaa bimaa shaa-a, wasi'a kursiyyuhus samaawaati wal arz, walaa ya-ooduhu hifzuhumaa, wahuwal 'aliyyul 'azeem.",
	"EnglishTranslate": "Allah there is no deity except Him, the Ever-Living, the Sustainer of [all] existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is [presently] before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.",
	"RomanUrduText": "Allaahu laa ilaaha illa huwal hayyul qayyoom, laa ta'khuzuhu sinatuw  walaa naum, lahu maa fis samaawaati wamaa fil arz, man zallazi yash-fa'ou 'indahu illa bi-iznih, ya'lamu maa baina aideehim wamaa khalfahum, walaa yuhitoona bishae-im min 'ilmihee illaa bimaa shaa-a, wasi'a kursiyyuhus samaawaati wal arz, walaa ya-ooduhu hifzuhumaa, wahuwal 'aliyyul 'azeem.",
	"RomanUrduTranslate":"Panah mangta hun mein Allah ki shaytan mardood se. Allah (woh hai ke) us ke siwa koi mabood nahi,woh zindah javed (aur) qaim o daaim hai usay onghaati hai na neend usi ka hai jo kuch asmano mein haiaur jo kuch zameen mein hai kon hai woh jo us keyahaan sifarish kar sakay magar us ki ijazat se? wohjaanta hai jo kuch logon ke samnay hai aur jo kuchhun ke peechay hai, aur woh us ke ilm mein se kisicheez ka ihata nahi kar saktay magar jis qadar wohkhud chahay, us ki kursi ne asmano aur zameen koghair rakha hai aur usay un dono ki hifazat nahithakaati aur woh buland tar nihayat azmat wala hai",
	"KannadaText": "ಅಲ್ಲಾಹು ಲಾ ಇಲಾಹ ಇಲ್ಲಾ ಹುವಲ್ ಹಯ್ಯುಲ್ ಕಯ್ಯೂಮ್, ಲಾ ತಅïಖುದುಹೂ ಸಿನತುನ್ ವಲಾ ನೌಮ್, ಲಹೂ ಮಾ ಫಿ ಸ್ಸಮಾವಾತಿ ವಮಾ ಫಿಲ್ ಅರ್ದ್, ಮನ್ ದಲ್ಲದೀ ಯಶ್‍ಫಉ ಇನ್ದಹೂ ಇಲ್ಲಾ ಬಿಇದ್‍ನಿಹ್, ಯಅïಲಮು ಮಾ ಬೈನ ಐದೀಹಿಮ್ ವಮಾ ಖಲ್ಫಹುಮ್ ವಲಾ ಯುಹೀತೂನ ಬಿಶೈಇನ್ ಮಿನ್ ಇಲ್ಮಿಹೀ ಇಲ್ಲಾ ಬಿಮಾ ಶಾಅï, ವಸಿಅ ಕುರ್ಸಿಯ್ಯುಹು ಸ್ಸಮಾವಾತಿ ವಲ್ ಅರ್ದ ವಲಾ ಯಊದುಹೂ ಹಿಫ್‍ದುಹುಮಾ, ವಹುವಲ್ ಅಲಿಯ್ಯುಲ್ ಅದೀಮ್ ",
	"KannadaTranslate":"ಅಲ್ಲಾಹ್! ಅವನಲ್ಲದೆ ಆರಾಧನೆಗೆ ನೈಜ ಹಕ್ಕುದಾರರಾಗಿ ಅನ್ಯರಿಲ್ಲ, ಅವನು ಎಂದೆಂದಿಗೂ ಬದುಕಿರುವವನೂ ಎಲ್ಲವನ್ನೂ ನಿಯಂತ್ರಿಸುವವನೂ ಆಗಿದ್ದಾನೆ. ತೂಕಡಿಕೆಯಾಗಲಿ ನಿದ್ರೆಯಾಗಲಿ ಅವನನ್ನು ಬಾಧಿಸದು. ಆಕಾಶಗಳಲ್ಲಿ ಮತ್ತು ಭೂಮಿಯಲ್ಲಿರುವುದೆಲ್ಲವೂ ಅವನದ್ದು. ಅವನ ಅನುಮತಿಯಿಲ್ಲದೆ ಅವನ ಬಳಿ ಶಿಫಾರಸು ಮಾಡುವವನು ಯಾರಿದ್ದಾನೆ? ಅವರ ಮುಂದಿರುವುದನ್ನೂ ಹಿಂದಿರುವುದನ್ನೂ ಅವನು ಅರಿಯುತ್ತಾನೆ. ಅವನ ಅರಿವಿನಿಂದ ಅವನು ಇಚ್ಛಿಸಿದ್ದನ್ನಲ್ಲದೆ ಬೇರೇನನ್ನೂ ಆವರಿಸಿಕೊಳ್ಳಲು ಅವರಿಗೆ ಸಾಧ್ಯವಿಲ್ಲ. ಅವನ ಕುರ್ಸೀ ಆಕಾಶಗಳನ್ನೂ ಭೂಮಿಯನ್ನೂ ವ್ಯಾಪಿಸಿದೆ. ಅವುಗಳ ಸಂರಕ್ಷಣೆಯು ಅವನಿಗೊಂದು ವಿಷಯವೇ ಅಲ್ಲ. ಅವನು ಅತ್ಯುನ್ನತನೂ ಮಹೋನ್ನತನೂ ಆಗಿದ್ದಾನೆ.",
	"Timing":"morningAndEvening",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/75.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "بِسْمِ اللهِ الرَّحْمَنِ الرَّحِيمِ ۞ قُلْ هُوَ اللهُ أَحَدٌ ۞ اللهُ الصَّمَدُ ۞ لَمْ يَلِدْ وَلَمْ يُولَدْ ۞ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ",
	"EnglishText": "Bismillaahir-Rahmaanir-Raheem. Qul Huwallaahu 'Ahad. Allaahus-Samad. Lam yalid wa lam yoolad. Wa lam yakun lahu kufuwan 'ahad.",
	"EnglishTranslate": " (1) Say, He is Allah, [who is] One,( 2 )   Allah, the Eternal Refuge.( 3 )   He neither begets nor is born,( 4 )   Nor is there to Him any equivalent.",
	"RomanUrduText": "Bismillaahir-Rahmaanir-Raheem. Qul Huwallaahu 'Ahad. Allaahus-Samad. Lam yalid wa lam yoolad. Wa lam yakun lahu kufuwan 'ahad.",
	"RomanUrduTranslate":"Allah taala ke naam se (shuru) jo nihayat meharban, bahot rahem karne wala hai {Aap keh dijiye ke woh Allah taala aik (hi) hai. Allah taala be niyaz hai. na us se koi paida huwa na woh kisi se paida huwa. aur na koi us ka humsar hai",
	"KannadaText": "ಕುಲ್ ಹುವಲ್ಲಾಹು ಅಹದ್, ಅಲ್ಲಾಹು ಸ್ಸಮದ್, ಲಮ್ ಯಲಿದ್ ವಲಮ್ ಯೂಲದ್, ವಲಮ್ ಯಕುಲ್ಲಹೂ ಕುಫುವನ್ ಅಹದ್. ",
	"KannadaTranslate":"ಹೇಳಿರಿ: ಅವನು ಅಲ್ಲಾಹು ಏಕೈಕನು. ಅಲ್ಲಾಹು ನಿರಾವಲಂಬಿಯೂ ಸರ್ವರಿಗೂ ಆಶ್ರಯದಾತನೂ ಆಗಿದ್ದಾನೆ. ಅವನಿಗೆ ಯಾವುದೇ ಸಂತಾನವಿಲ್ಲ, ಅವನು ಯಾರ ಸಂತಾನವೂ ಅಲ್ಲ. ಅವನಿಗೆ ಸರಿಸಾಟಿಯಾಗಿ ಯಾರೂ ಇಲ್ಲ.",
	"Timing":"morningAndEvening",
	"Repeat": 3,
	"Audio": "http://www.hisnmuslim.com/audio/ar/76.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "بِسْمِ اللهِ الرَّحْمَنِ الرَّحِيمِ۞ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۞ مِنْ شَرِّ مَا خَلَقَ ۞ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۞ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۞ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ",
	"EnglishText": "Bismillaahir-Rahmaanir-Raheem.Qul a'oozu birabbil falaq. Min sharri maa khalaq. Wa min sharri ghaasiqin izaa waqab. Wa  sharrin naffaasaati fil 'uqad. Wa min sharri haasidin izaa hasad.",
	"EnglishTranslate": "",
	"RomanUrduText": "Bismillaahir-Rahmaanir-Raheem.Qul a'oozu birabbil falaq. Min sharri maa khalaq. Wa min sharri ghaasiqin izaa waqab. Wa  sharrin naffaasaati fil 'uqad. Wa min sharri haasidin izaa hasad.",
	"RomanUrduTranslate":"Allah taala ke naam se (shuru) jo nihayat meharban, bahot rahem karne wala hai {Aap keh dijiye! ke mein subah ke Rab ki panah mein aata hun. us cheez ke shar se jo us ne paida ki hai. aur andhera karne walay ke shar se jab woh chup jaye aur un ke shar se jo girhon mein phoonknay wali hain. aur hasad karne walay ke shar se bhi jab woh hasad kare.",
	"KannadaText": "ಕುಲ್ ಅಊದು ಬಿರಬ್ಬಿಲ್ ಫಲಕ್, ಮಿನ್ ಶರ್ರಿ ಮಾ ಖಲಕ್, ವಮಿನ್ ಶರ್ರಿ ಗಾಸಿಕಿನ್ ಇದಾ ವಕಬ್, ವಮಿನ್ ಶರ್ರಿ ನ್ನಪ್ಫಾಸಾತಿ ಫಿಲ್ ಉಕದ್, ವಮಿನ್ ಶರ್ರಿ ಹಾಸಿದಿನ್ ಇದಾ ಹಸದ್.",
	"KannadaTranslate":"ಹೇಳಿರಿ: ಪ್ರಭಾತದ ರಬ್ಬ್‍ನೊಂದಿಗೆ ಅವನು ಸೃಷ್ಟಿಸಿದ ಕೆಡುಕಿನಿಂದ, ರಾತ್ರಿಯು ಆವರಿಸುವಾಗ ಅದರ ಕೆಡುಕಿನಿಂದ, ಗಂಟುಗಳಲ್ಲಿ ಊದುವವರ ಕೆಡುಕಿನಿಂದ ಮತ್ತು ಅಸೂಯೆಗಾರನು ಅಸೂಯೆಪಡುವಾಗ ಅವನ ಕೆಡುಕಿನಿಂದ ನಾನು ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ.",
	"Repeat": 3,
	"Audio": "http://www.hisnmuslim.com/audio/ar/76.mp3"
	},
	{
	"Id": 1,
	"ArabicText": " بِسْمِ اللهِ الرَّحْمَنِ الرَّحِيم ۞ قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۞ مَلِكِ النَّاسِ ۞ إِلَهِ النَّاسِ ۞ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۞ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۞ مِنَ الْجِنَّةِ وَالنَّاسِ",
	"EnglishText": "Bismillaahir-Rahmaanir-Raheem. Qul a'oozu birabbin naas. Malikin naas. Ilaahin naas. Min sharril waswaasil khannaas. Allazi yuwaswisu fee sudoorin naas. Minal jinnati wannaas.",
	"EnglishTranslate": " 1) Say, I seek refuge in the Lord of mankind,( 2 )   The Sovereign of mankind.( 3 )   The God of mankind,( 4 )   From the evil of the retreating whisperer -( 5 )   Who whispers [evil] into the breasts of mankind -( 6 )   From among the jinn and mankind.",
	"RomanUrduText": "Bismillaahir-Rahmaanir-Raheem. Qul a'oozu birabbin naas. Malikin naas. Ilaahin naas. Min sharril waswaasil khannaas. Allazi yuwaswisu fee sudoorin naas. Minal jinnati wannaas.",
	"RomanUrduTranslate":"Qul 'a'oothu birabbin-naas. Malikin-naas. 'Ilaahin-naas. Min sharril-waswaasil-khannaas. Allathee yuwaswisu fee sudoorin-naas. Minal-jinnati wannaas.",
	"KannadaText": "ಕುಲ್ ಅಊದು ಬಿರಬ್ಬಿ ನ್ನಾಸ್, ಮಲಿಕಿ ನ್ನಾಸ್, ಇಲಾಹಿ ನ್ನಾಸ್, ಮಿನ್ ಶರ್ರಿಲ್ ವಸ್ವಾಸಿಲ್ ಖನ್ನಾಸ್, ಅಲ್ಲದೀ ಯುವಸ್ವಿಸು ಫೀ ಸುದೂರಿ ನ್ನಾಸ್, ಮಿನಲ್ ಜಿನ್ನತಿ ವನ್ನಾಸ್ (ಮೂರು ಸಲ)",
	"KannadaTranslate":"ಹೇಳಿರಿ: ಜನರ ರಬ್ಬ್‍ನೊಂದಿಗೆ, ಜನರ ಸಾಮ್ರಾಟನೊಂದಿಗೆ, ಜನರ ಆರಾಧ್ಯನೊಂದಿಗೆ, ಮನುಷ್ಯರ ಹೃದಯಗಳಲ್ಲಿ ದುರ್ಬೋಧನೆ ಮಾಡಿ ಹಿಂದಕ್ಕೆ ಸರಿಯುವ ಮತ್ತು ಮನುಷ್ಯರು ಹಾಗೂ ಜಿನ್ನ್‍ಗಳಲ್ಲಿ ಸೇರಿದ ದುರ್ಬೋಧಕರ 	ಕೆಡುಕಿನಿಂದ ನಾನು ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ",
	"Timing":"morningAndEvening",
	"Repeat": 3,
	"Audio": "http://www.hisnmuslim.com/audio/ar/76.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَهَ إلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذَا الْيَوْمِ وَخَيرَ مَا بَعْدَهُ ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي  هَذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ، رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ، رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ",
	"EnglishText": "'Asbahnaa wa 'asbahal-mulku lillaahi walhamdu lillaahi, laa 'ilaaha 'illallaahu wahdahu laa shareeka lahu, lahul-mulku wa lahul-hamdu wa Huwa 'alaa kulli shay'in Qadeer. Rabbi 'as'aluka khayra maa fee haathal-yawmi wa khayra maa ba'dahu wa a'oothu bika min sharri maa fee haathal-yawmi wa sharri maa ba'dahu, Rabbi 'a'oothu bika minal-kasali, wa soo'il-kibari, Rabbi 'a'oothu bika min 'athaabin fin-naari wa 'athaabin fil-qabri.",
	"EnglishTranslate":"We have reached the morning and at this very time unto Allaah, belongs all sovereignty , and all praise is for Allaah. None has the right to be worshipped except Allaah, alone, without any partner, to Him belong all sovereignty and praise and He is over all things omnipotent. My Lord, I ask You for the good of this day and the good of what follows it and I take refuge in You from the evil of this day and the evil of what follows it . My Lord, I take refuge in You from laziness and senility. My Lord, I take refuge in You from torment in the Fire and punishment in the grave.",
	"RomanUrduText": "Asbahna wa-asbahal-mulku lillah walhamdu lillah la ilaha illal-lah, wahdahu la shareeka lah, lahul-mulku walahul-hamd, wahuwa AAala kulli shayin qadeer, rabbi as-aluka khayra ma fee hathihil-laylah, wakhayra ma baAAdaha, wa-aAAoothu bika min sharri hathihil-laylah, washarri ma baAAdaha, rabbi aAAoothu bika minal-kasal, wasoo-il kibar, rabbi aAAoothu bika min AAathabin fin-nar, waAAathabin fil-qabr.",
	"RomanUrduTranslate":"Ham ne subah ki aur Allah ke saaray mulk ne subah ki aur sab tareef Allah hi ke liye hai Allah ke siwa koi mabood nahi woh akela hai, us ka koi shareek nahi usi ki badshahat hai aur usi ke liye sab tareef hai aur woh har cheez par kaamil qudrat rakhta hai. Ae mere Rab! mein tujh se is din114, ki behtari ka sawal karta hun aur us din ki behtari jo is ke baad anay wala hai aur mein is din115 ke shar se teri panah mein aata hun aur is ke baad anay walay din ke shar se, ae mere Rab! mein kahili [aur burhapay ki kharabi] se teri panah mein aata hun. Ae mere Rab! mein aag ke azaab se aur qabr ke azaab se teri panah mein aata hun.",
	"KannadaText": "ಅಸ್ಬಹ್‍ನಾ ವಅಸ್ಬಹಲ್ ಮುಲ್ಕು ಲಿಲ್ಲಾಹಿ, ವಲ್‍ಹಮ್ದು ಲಿಲ್ಲಾಹಿ, ಲಾ ಇಲಾಹ ಇಲ್ಲಲ್ಲಾಹು ವಹ್ದಹೂ ಲಾ ಶರೀಕ ಲಹೂ, ಲಹುಲ್ ಮುಲ್ಕು ವಲಹುಲ್ ಹಮ್ದು ವಹುವ ಅಲಾ ಕುಲ್ಲಿ ಶೈಇನ್ ಕದೀರುನ್, ರಬ್ಬಿ ಅಸ್‍ಅಲುಕ ಖೈರ ಮಾ ಫೀ ಹಾದಲ್ ಯೌಮಿ ವಖೈರ ಮಾ ಬಅïದಹೂ, ವಅಊದು ಬಿಕ ಮಿನ್ ಶರ್ರಿ ಮಾ ಫೀ ಹಾದಲ್ ಯೌಮಿ ವಶರ್ರಿ ಮಾ ಬಅïದಹೂ, ರಬ್ಬಿ ಅಊದು ಬಿಕ ಮಿನಲ್ ಕಸಲಿ ವಸೂಇಲ್ ಕಿಬರಿ, ರಬ್ಬಿ ಅಊದು ಬಿಕ ಮಿನ್ ಅದಾಬಿನ್ ಫಿನ್ನಾರಿ ವಅದಾಬಿನ್ ಫಿಲ್ ಕಬ್ರ್ ",
	"KannadaTranslate":"ನಾವು ಬೆಳಗನ್ನು ಪ್ರವೇಶಿಸಿದೆವು ಮತ್ತು ಅಲ್ಲಾಹನ ಸಂಪೂರ್ಣ ಆಧಿಪತ್ಯವು ಬೆಳಗನ್ನು ಪ್ರವೇಶಿಸಿದೆ. ಮತ್ತು ಸ್ತುತಿಯು ಅಲ್ಲಾಹನಿಗೆ. ಅಲ್ಲಾಹನಲ್ಲದೆ ಆರಾಧನೆಗೆ ನೈಜ ಹಕ್ಕುದಾರರಾಗಿ ಅನ್ಯರಿಲ್ಲ, ಅವನು ಏಕೈಕನೂ ಸಹಭಾಗಿರಹಿತನೂ ಆಗಿದ್ದಾನೆ. ಆಧಿಪತ್ಯವು ಅವನದ್ದು ಮತ್ತು ಸ್ತುತಿಯು ಅವನಿಗೆ. ಅವನು ಎಲ್ಲಾ ವಿಷಯಗಳಲ್ಲೂ ಸಾಮರ್ಥ್ಯವುಳ್ಳವನು. ನನ್ನ ರಬ್ಬೇ! ಈ ದಿನದಲ್ಲಿರುವ ಒಳಿತನ್ನು ಮತ್ತು ಇದರ ನಂತರದ ದಿನಗಳಲ್ಲಿರುವ ಒಳಿತನ್ನು ನಾನು ನಿನ್ನೊಂದಿಗೆ ಬೇಡುತ್ತಿದ್ದೇನೆ. ಈ ದಿನದ ಕೆಡುಕಿನಿಂದ ಮತ್ತು ಇದರ ನಂತರದ ದಿನಗಳಲ್ಲಿರುವ ಕೆಡುಕಿನಿಂದ ನಾನು ನಿನ್ನೊಂದಿಗೆ ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ. ನನ್ನ ರಬ್ಬೇ! ಸೋಮಾರಿತನದಿಂದ ಮತ್ತು ವೃದ್ಧಾಪ್ಯ ವೈಷಮ್ಯದಿಂದ ನಾನು ನಿನ್ನೊಂದಿಗೆ ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ. ನನ್ನ ರಬ್ಬೇ! ನರಕದಲ್ಲಿರುವ ಶಿಕ್ಷೆಯಿಂದ ಮತ್ತು ಗೋರಿಯಲ್ಲಿರುವ ಶಿಕ್ಷೆಯಿಂದ ನಾನು ನಿನ್ನೊಂದಿಗೆ ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ.",
	"Timing":"morning",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/77.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "اَمْسَيْنَا وَاَمْسَ الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِيْ هَذَا اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهُ، وَأَعُوْذُ بِكَ مِنْ شَرِّ مَا فِي هَذَا اللَّيْلَةِ وَشَرِّ مَا بَعْدَهُ، رَبِّ أَعُوْذُ بِكَ مِنَ الْكَسَلِ، وَسُوءِ الْكِبَرِ، رَبِّ أَعُوْذُ بِكَ مِنْ عَذَابٍ فِيْ النَّارِ وَعَذَابٍ فِيْ الْقَبْرِ",
	"EnglishText": "Amsayna wa-amsal-mulku lillah walhamdu lillah la ilaha illal-lah, wahdahu la shareeka lah, lahul-mulku walahul-hamd, wahuwa AAala kulli shayin qadeer, rabbi as-aluka khayra ma fee hathihil-laylah, wakhayra ma baAAdaha, wa-aAAoothu bika min sharri hathihil-laylah, washarri ma baAAdaha, rabbi aAAoothu bika minal-kasal, wasoo-il kibar, rabbi aAAoothu bika min AAathabin fin-nar, waAAathabin fil-qabr.",
	"EnglishTranslate":"We have reached the evening and at this very time unto Allah belongs all sovereignty, and all praise is for Allah. None has the right to be worshipped except Allah, alone, without a partner, to Him belongs all sovereignty and praise and He is over all things omnipotent. My Lord, I ask You for the good of this night and the good of what follows it and I take refuge in You from the evil of this night and the evil of what follows it. My Lord, I take refuge in You from laziness and senility. My Lord, I take refuge in You from torment in the Fire and punishment in the grave.",
	"RomanUrduText": "Amsayna wa-amsal-mulku lillah walhamdu lillah la ilaha illal-lah, wahdahu la shareeka lah, lahul-mulku walahul-hamd, wahuwa AAala kulli shayin qadeer, rabbi as-aluka khayra ma fee hathihil-laylah, wakhayra ma baAAdaha, wa-aAAoothu bika min sharri hathihil-laylah, washarri ma baAAdaha, rabbi aAAoothu bika minal-kasal, wasoo-il kibar, rabbi aAAoothu bika min AAathabin fin-nar, waAAathabin fil-qabr.",
	"RomanUrduTranslate":"",
	"KannadaText": "ಅಮ್ಸಯ್ನಾ ವ ಅಮ್ಸಲ್ ಮುಲ್ಕು ಲಿಲ್ಲಾಹಿ, ವಲ್‍ಹಮ್ದು ಲಿಲ್ಲಾಹಿ, ಲಾ ಇಲಾಹ ಇಲ್ಲಲ್ಲಾಹು ವಹ್ದಹೂ ಲಾ ಶರೀಕ ಲಹೂ, ಲಹುಲ್ ಮುಲ್ಕು ವಲಹುಲ್ ಹಮ್ದು ವಹುವ ಅಲಾ ಕುಲ್ಲಿ ಶೈಇನ್ ಕದೀರುನ್, ರಬ್ಬಿ ಅಸ್‌ಅಲುಕ ಖೈರ ಮಾಫೀ ಹಾದಿಹಿ ಲ್ಲೆöÊಲತಿ ವ ಖೈರ ಮಾ ಬಅï‌ದಹಾ ವ ಅಊದು ಬಿಕ ಮಿನ್ ರ‍್ರಿ ಮಾಫೀ ಹಾದಿಹಿ ಲ್ಲೆöÊಲತಿ ವ ರ‍್ರಿ ಮಾ ಬಅï‌ದಹಾ , ರಬ್ಬಿ ಅಊದು ಬಿಕ ಮಿನಲ್ ಕಸಲಿ ವಸೂಇಲ್ ಕಿಬರಿ, ರಬ್ಬಿ ಅಊದು ಬಿಕ ಮಿನ್ ಅದಾಬಿನ್ ಫಿನ್ನಾರಿ ವಅದಾಬಿನ್ ಫಿಲ್ ಕಬ್ರ್ ",
	"KannadaTranslate":"ನಾವು ಸಂಜೆಯನ್ನು ಪ್ರವೇಶಿಸಿದೆವು ಮತ್ತು ಅಲ್ಲಾಹನ ಸಂಪೂರ್ಣ ಆಧಿಪತ್ಯವು ಸಂಜೆಯನ್ನು ಪ್ರವೇಶಿಸಿದೆ. ಮತ್ತು ಸ್ತುತಿಯು ಅಲ್ಲಾಹನಿಗೆ. ಅಲ್ಲಾಹನಲ್ಲದೆ ಆರಾಧನೆಗೆ ನೈಜ ಹಕ್ಕುದಾರರಾಗಿ ಅನ್ಯರಿಲ್ಲ, ಅವನು ಏಕೈಕನೂ ಸಹಭಾಗಿರಹಿತನೂ ಆಗಿದ್ದಾನೆ. ಆಧಿಪತ್ಯವು ಅವನದ್ದು ಮತ್ತು ಸ್ತುತಿಯು ಅವನಿಗೆ. ಅವನು ಎಲ್ಲಾ ವಿಷಯಗಳಲ್ಲೂ ಸಾಮರ್ಥ್ಯವುಳ್ಳವನು. ನನ್ನ ರಬ್ಬೇ! ಈ ರಾತ್ರಿಯಲ್ಲಿರುವ ಒಳಿತನ್ನು ಮತ್ತು ಇದರ ನಂತರದ ರಾತ್ರಿಗಳಲ್ಲಿರುವ ಒಳಿತನ್ನು ನಾನು ನಿನ್ನೊಂದಿಗೆ ಬೇಡುತ್ತಿದ್ದೇನೆ. ಈ ರಾತ್ರಿಯ ಕೆಡುಕಿನಿಂದ ಮತ್ತು ಇದರ ನಂತರದ ರಾತ್ರಿಗಳಲ್ಲಿರುವ ಕೆಡುಕಿನಿಂದ ನಾನು ನಿನ್ನೊಂದಿಗೆ ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ. ನನ್ನ ರಬ್ಬೇ! ಸೋಮಾರಿತನದಿಂದ ಮತ್ತು ವೃದ್ಧಾಪ್ಯ ವೈಷಮ್ಯದಿಂದ ನಾನು ನಿನ್ನೊಂದಿಗೆ ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ. ನನ್ನ ರಬ್ಬೇ! ನರಕದಲ್ಲಿರುವ ಶಿಕ್ಷೆಯಿಂದ ಮತ್ತು ಗೋರಿಯಲ್ಲಿರುವ ಶಿಕ್ಷೆಯಿಂದ ನಾನು ನಿನ್ನೊಂದಿಗೆ ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ.",
	"Timing":"evening",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/77.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا ، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ",
	"EnglishText": "Allahumma bika asbahna wabika  amsayna, wabika nahya ,wabika namootu wa-ilaykan-nushoor.",
	"EnglishTranslate": "O Allah, by Your leave we have reached the evening and by Your leave we have reached the morning, by Your leave we live and die and unto You is our return.",
	"RomanUrduText": "Allahumma bika asbahna wabika  amsayna, wabika nahya ,wabika namootu wa-ilaykan-nushoor.",
	"RomanUrduTranslate":"Ae Allah! teri hi hifazat mein ham ne subah ki aur teri hi hifazat mein shaam ki aur tairay hi naam par ham zindah hotay hain aur tairay hi naam par ham martay hain. aur teri hi taraf lautna hai.",
	"KannadaText": "ಅಲ್ಲಾಹುಮ್ಮ ಬಿಕ ಅಸ್ಬಹ್‍ನಾ ವಬಿಕ ಅಮ್ಸೈನಾ ವಬಿಕ ನಹ್ಯಾ ವಬಿಕ ನಮೂತು ವಇಲೈಕ ನ್ನುಶೂರ್ ",
	"KannadaTranslate":"ಓ ಅಲ್ಲಾಹ್! ನಿನ್ನಿಂದಾಗಿ ನಾವು ಬೆಳಗನ್ನು ಪ್ರವೇಶಿಸಿದೆವು, ನಿನ್ನಿಂದಾಗಿ ನಾವು ಸಂಜೆಯನ್ನು ಪ್ರವೇಶಿಸಿದೆವು, ನಿನ್ನಿಂದಾಗಿ ನಾವು ಬದುಕುತ್ತಿದ್ದೇವೆ, ನಿನ್ನಿಂದಾಗಿ ನಾವು ಮರಣವನ್ನು ಹೊಂದುತ್ತೇವೆ ಮತ್ತು ಪುನರುತ್ಥಾನವು ನಿನ್ನ ಬಳಿಗೇ ಆಗಿದೆ.",
	"Timing":"morning",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/78.mp3"
},
{
	"Id": 1,
	"ArabicText": "اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ وَإِلَـيْكَ المَصِيْر",
	"EnglishText": "Allahumma bika amsayna, wabika asbahna, wabika nahya wabika namootu wa-ilaykal-maseer.",
	"EnglishTranslate": "O Allah, by Your leave we have reached the evening and by Your leave, we have reached the morning, by Your leave we live and die and unto You is our return.",
	"RomanUrduText": "Allahumma bika amsayna, wabika asbahna, wabika nahya wabika namootu wa-ilaykal-maseer.",
	"RomanUrduTranslate":"Aye Allah! Ham ne tairay hi hukm se shaam ki aur tairay hi hukm se subah ki thi, tairay hi hukm se ham zindah hain aur tera jab hukm ho ga, ham mar jayen ge aur teri hi taraf lautna hai",
	"KannadaText": "ಅಲ್ಲಾಹುಮ್ಮ ಬಿಕ ಅಮ್ಸಯ್ನಾ ವಬಿಕ ಅಸ್‌ಬಹ್‌ನಾ ವಬಿಕ ನಹ್ಯಾ ವಬಿಕ ನಮೂತು ವ ಇಲೈಕಲ್ ಮಸೀರ್",
	"KannadaTranslate":"ಓ ಅಲ್ಲಾಹ್! ನಿನ್ನಿಂದಾಗಿ ನಾವು ಸಂಜೆಯನ್ನು ಪ್ರವೇಶಿಸಿದೆವು, ನಿನ್ನಿಂದಾಗಿ ನಾವು ಬೆಳಗನ್ನು ಪ್ರವೇಶಿಸಿದೆವು, ನಿನ್ನಿಂದಾಗಿ ನಾವು ಬದುಕುತ್ತಿದ್ದೇವೆ, ನಿನ್ನಿಂದಾಗಿ ನಾವು ಮರಣವನ್ನು ಹೊಂದುತ್ತೇವೆ ಮತ್ತು ಪುನರುತ್ಥಾನವು ನಿನ್ನ ಬಳಿಗೇ ಆಗಿದೆ.",
	"Timing":"evening",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/78.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لاَ يَغْفِرُ الذُّنوبَ إِلاَّ أَنْتَ",
	"EnglishText": "Allahumma anta rabbee la ilaha illa ant, khalaqtanee wa-ana AAabduk, wa-ana AAala AAahdika wawaAAdika mas-tataAAt, aAAoothu bika min sharri ma sanaAAt, aboo-o laka biniAAmatika AAalay, wa-aboo-o bithanbee, faghfir lee fa-innahu la yaghfiruth-thunooba illa ant.",
	"EnglishTranslate": "O Allah, You are my Lord, none has the right to be worshipped except You, You created me and I am Your servant and I abide to Your covenant and promise as best I can, I take refuge in You from the evil of which I have committed.  I acknowledge Your favour upon me and I acknowledge my sin, so forgive me, for verily none can forgive sin except You.",
	"RomanUrduText": "Allahumma anta rabbee la ilaha illa ant, khalaqtanee wa-ana AAabduk, wa-ana AAala AAahdika wawaAAdika mas-tataAAt, aAAoothu bika min sharri ma sanaAAt, aboo-o laka biniAAmatika AAalay, wa-aboo-o bithanbee, faghfir lee fa-innahu la yaghfiruth-thunooba illa ant.",
	"RomanUrduTranslate":"Ae Allah! Tu hi mera Rab hai tairay siwa koi mabood nahi Tu ne mujhe paida farmaya, aur mein tera bandah hun aur mein apni taaqat ke mutabiq tairay ahed aur waday par qaim hun mein tujh se us cheez ke shar se panah mangta hun jis ka mein ne irtikaab kiya, mein tairay samnay tairay inaam ka iqraar karta hun jo mujh par huwa aur mein apne gunaaho ka iqraar karta hun, lehaza Tu mujhe maaf kardey. waqea yeh hai ke tairay siwa koi gunaaho ko maaf nahi karsaktha",
	"KannadaText": "ಅಲ್ಲಾಹುಮ್ಮ ಅನ್ತ ರಬ್ಬೀ ಲಾ ಇಲಾಹ ಇಲ್ಲಾ ಅನ್ತ ಖಲಕ್ತನೀ ವಅನ ಅಬ್ದುಕ, ವಅನ ಅಲಾ ಅಹ್ದಿಕ ವವಅïದಿಕ ಮಸ್ತತಅïತು, ಅಊದು ಬಿಕ ಮಿನ್ ಶರ್ರಿ ಮಾ ಸನಅïತು, ಅಬೂಉ ಲಕ ಬಿನಿಅïಮತಿಕ ಅಲಯ್ಯ, ವಅಬೂಉ ಬಿದಮ್ಬೀ ಫಗ್‍ಫಿರ್ ಲೀ ಇನ್ನಹೂ ಲಾ ಯಗ್‍ಫಿರು ದ್ದುನೂಬ ಇಲ್ಲಾ ಅನ್ತ್",
	"KannadaTranslate":"ಓ ಅಲ್ಲಾಹ್! ನೀನು ನನ್ನ ರಬ್ಬ್. ನೀನಲ್ಲದೆ ಆರಾಧನೆಗೆ ನೈಜ ಹಕ್ಕುದಾರರಾಗಿ ಅನ್ಯರಿಲ್ಲ. ನೀನು ನನ್ನನ್ನು ಸೃಷ್ಟಿಸಿರುವೆ ಮತ್ತು ನಾನು ನಿನ್ನ ದಾಸನಾಗಿರುವೆನು. ನನಗೆ ಸಾಧ್ಯವಾಗುವಷ್ಟರ ಮಟ್ಟಿಗೆ ನಾನು ನಿನ್ನ ಕರಾರು ಮತ್ತು ವಾಗ್ದಾನವನ್ನು ಪಾಲಿಸುತ್ತಿರುವೆನು. ನಾನು ಮಾಡಿದ ಕರ್ಮಗಳ ಕೆಡುಕಿನಿಂದ ನಾನು ನಿನ್ನೊಂದಿಗೆ ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ. ನೀನು ನನ್ನ ಮೇಲೆ ಸುರಿಸಿದ ಅನುಗ್ರಹಗಳಿಗಾಗಿ ನಾನು ನಿನಗೆ ಶರಣಾಗುತ್ತಿರುವೆ. ಮತ್ತು ನನ್ನ ಪಾಪಗಳಿಂದಾಗಿ ನಾನು ನಿನಗೆ ಶರಣಾಗುತ್ತಿರುವೆ. ಆದ್ದರಿಂದ ನನಗೆ ಕ್ಷಮೆ ನೀಡು. ಖಂಡಿತವಾಗಿಯೂ ನೀನಲ್ಲದೆ ಪಾಪಗಳನ್ನು ಕ್ಷಮಿಸುವವರಿಲ್ಲ.",
	"Timing":"morningAndEvening",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/79.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "اللَّهُمَّ إِنِّي أَصْبَحْتُ أُشْهِدُكَ، وَأُشْهِدُ حَمَلَةَ عَرْشِكَ، وَمَلاَئِكَتِكَ، وَجَمِيعَ خَلْقِكَ، أَنَّكَ أَنْتَ اللَّهُ لَا إِلَهَ إِلاَّ أَنْتَ وَحْدَكَ لاَ شَرِيكَ لَكَ، وَأَنَّ مُحَمَّداً عَبْدُكَ وَرَسُولُكَ (أربعَ مَرَّاتٍ)",
	"EnglishText": "Allahumma innee asbahtu oshhiduk, wa-oshhidu hamalata AAarshik, wamala-ikatak, wajameeAAa khalqik, annaka antal-lahu la ilaha illa ant, wahdaka la shareeka lak, wa-anna Muhammadan AAabduka warasooluk.",
	"EnglishTranslate": "O Allah, verily I have reached the morning and call on You, the bearers of Your throne, Your angles, and all of Your creation to witness that You are Allah, none has the right to be worshipped except You, alone, without partner and that Muhammad is Your Servant and Messenger.",
	"RomanUrduText": "Allahumma innee asbahtu oshhiduk, wa-oshhidu hamalata AAarshik, wamala-ikatak, wajameeAAa khalqik, annaka antal-lahu la ilaha illa ant, wahdaka la shareeka lak, wa-anna Muhammadan AAabduka warasooluk.",
	"RomanUrduTranslate":"Ae Allah! yaqeenan mein ne aisi haalat mein subah ki ke tujhe, tera arsh uthany walay farishton, tairay (deegar) farishton aur teri tamam makhlooq ko is baat par gawah banata hun ke Tu hi Allah hai, tairay siwa koi mabood nahi Tu akela hai, tera koi shareek nahi aur bilaa shuba Mohammad tairay bande aur tairay Rasool hain.",
	"KannadaText": "ಅಲ್ಲಾಹುಮ್ಮ ಇನ್ನೀ ಅಸ್ಬಹ್ತು, ಉಶ್‍ಹಿದುಕ ವಉಶ್‍ಹಿದು ಹಮಲತ ಅರ್ಶಿಕ, ವಮಲಾಇಕತಕ, ವಜಮೀಅ ಖಲ್ಕಿಕ, ಅನ್ನಕ ಅನ್ತಲ್ಲಾಹು ಲಾ ಇಲಾಹ ಇಲ್ಲಾ ಅನ್ತ ವಹ್ದಕ ಲಾ ಶರೀಕ ಲಕ, ವಅನ್ನ ಮುಹಮ್ಮದನ್ ಅಬ್ದುಕ ವರಸೂಲುಕ್ (ನಾಲ್ಕು ಸಲ)",
	"KannadaTranslate":"ಓ ಅಲ್ಲಾಹ್! ನೀನು ಅಲ್ಲಾಹನಾಗಿರುವೆ, ನಿನ್ನ ಹೊರತು ಆರಾಧನೆಗೆ ನೈಜ ಹಕ್ಕುದಾರರಾಗಿ ಅನ್ಯರಿಲ್ಲ. ನೀನು ಏಕೈಕನೂ ಸಹಭಾಗಿರಹಿತನೂ ಆಗಿರುವೆ, ಮತ್ತು ಮುಹಮ್ಮದ್ ನಿನ್ನ ದಾಸರೂ ರಸೂಲರೂ ಆಗಿರುವರು ನಿನ್ನನ್ನು ಸಾಕ್ಷಿಯಾಗಿಸುತ್ತಾ, ನಿನ್ನ ಅರ್ಶನ್ನು ಹೊರುವವರನ್ನು, ನಿನ್ನ ಮಲಕ್‍ಗಳನ್ನು ಮತ್ತು ನಿನ್ನ ಸಂಪೂರ್ಣ ಸೃಷ್ಟಿಯನ್ನು ಸಾಕ್ಷಿಯಾಗಿಸುತ್ತಾ ನಾನು ಬೆಳಗನ್ನು ಪ್ರವೇಶಿಸಿದ್ದೇನೆ.",
	"Timing":"morning",
	"Repeat": 4,
	"Audio": "http://www.hisnmuslim.com/audio/ar/80.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "اللَّهُمَّ إِنِّي أَمْسَيْتُ أُشْهِدُكَ وَأُشْهِدُ حَمَلَةَ عَرْشِكَ، وَمَلَائِكَتَكَ وَجَمِيعَ خَلْقِكَ، أَنَّكَ أَنْتَ اللهُ لَا إِلَهَ إِلَّا أَنْتَ وَحْدَكَ لَا شَرِيكَ لَكَ، وَأَنَّ مُحَمَّداً عَبْدُكَ وَرَسُولُكَ (أربعَ مَرَّاتٍ)",
	"EnglishText": "Allahumma innee amsaytu oshhiduk, wa-oshhidu hamalata AAarshik, wamala-ikatak, wajameeAAa khalqik, annaka antal-lahu la ilaha illa ant, wahdaka la shareeka lak, wa-anna Muhammadan AAabduka warasooluk.",
	"EnglishTranslate": "O Allah, verily I have reached the morning and call on You, the bearers of Your throne, Your angles, and all of Your creation to witness that You are Allah, none has the right to be worshipped except You, alone, without partner and that Muhammad is Your Servant and Messenger.",
	"RomanUrduText": "Allahumma innee amsaytu oshhiduk, wa-oshhidu hamalata AAarshik, wamala-ikatak, wajameeAAa khalqik, annaka antal-lahu la ilaha illa ant, wahdaka la shareeka lak, wa-anna Muhammadan AAabduka warasooluk.",
	"RomanUrduTranslate":"Ae Allah! yaqeenan mein ne aisi haalat mein shaam ki ke tujhe, tera arsh uthany walay farishton, tairay (deegar) farishton aur teri tamam makhlooq ko is baat par gawah banata hun ke Tu hi Allah hai, tairay siwa koi mabood nahi Tu akela hai, tera koi shareek nahi aur bilaa shuba Mohammad tairay bande aur tairay Rasool hain",
	"KannadaText": "ಅಲ್ಲಾಹುಮ್ಮ ಇನ್ನೀ ಅಮ್ಸಯ್ತು, ಉಶ್‍ಹಿದುಕ ವಉಶ್‍ಹಿದು ಹಮಲತ ಅರ್ಶಿಕ, ವಮಲಾಇಕತಕ, ವಜಮೀಅ ಖಲ್ಕಿಕ, ಅನ್ನಕ ಅನ್ತಲ್ಲಾಹು ಲಾ ಇಲಾಹ ಇಲ್ಲಾ ಅನ್ತ ವಹ್ದಕ ಲಾ ಶರೀಕ ಲಕ, ವಅನ್ನ ಮುಹಮ್ಮದನ್ ಅಬ್ದುಕ ವರಸೂಲುಕ್ (ನಾಲ್ಕು ಸಲ)",
	"KannadaTranslate":"ಓ ಅಲ್ಲಾಹ್! ನೀನು ಅಲ್ಲಾಹನಾಗಿರುವೆ, ನಿನ್ನ ಹೊರತು ಆರಾಧನೆಗೆ ನೈಜ ಹಕ್ಕುದಾರರಾಗಿ ಅನ್ಯರಿಲ್ಲ. ನೀನು ಏಕೈಕನೂ ಸಹಭಾಗಿರಹಿತನೂ ಆಗಿರುವೆ, ಮತ್ತು ಮುಹಮ್ಮದ್( ನಿನ್ನ ದಾಸರೂ ರಸೂಲರೂ ಆಗಿರುವರು ನಿನ್ನನ್ನು ಸಾಕ್ಷಿಯಾಗಿಸುತ್ತಾ, ನಿನ್ನ ಅರ್ಶನ್ನು ಹೊರುವವರನ್ನು, ನಿನ್ನ ಮಲಕ್‍ಗಳನ್ನು ಮತ್ತು ನಿನ್ನ ಸಂಪೂರ್ಣ ಸೃಷ್ಟಿಯನ್ನು ಸಾಕ್ಷಿಯಾಗಿಸುತ್ತಾ ನಾನು ಸಂಜೆಯನ್ನು ಪ್ರವೇಶಿಸಿದ್ದೇನೆ.",
	"Timing":"evening",
	"Repeat": 4,
	"Audio": "http://www.hisnmuslim.com/audio/ar/80.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "اللَّهُمَّ مَا أَصْبَحَ بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لاَ شَرِيكَ لَكَ، فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ",
	"EnglishText": "Allahumma ma asbaha bee min niAAmatin, aw bi-ahadin min khalqik, faminka wahdaka la shareeka lak, falakal-hamdu walakash-shukr.",
	"EnglishTranslate": "O Allah, what blessing I or any of Your creation have risen upon, is from You alone, without partner, so for You is all praise and unto You all thanks.",
	"RomanUrduText": "Allahumma ma asbaha bee min niAAmatin, aw bi-ahadin min khalqik, faminka wahdaka la shareeka lak, falakal-hamdu walakash-shukr.",
	"RomanUrduTranslate":"Ae Allah! subah ke waqt, mujh par ya teri makhlooq mein se kisi par jo bhi inaam huwa hai, woh teri hi taraf se hai, Tu akela hai, tera koi shareek nahi, pas tairay hi liye sab tareef hai aur tairay hi liye shukr hai.",
	"KannadaText": "ಅಲ್ಲಾಹುಮ್ಮ ಮಾ ಅಸ್ಬಹ ಬೀ ಮಿನ್ ನಿಅïಮತಿನ್ ಅವ್ ಬಿಅಹದಿನ್ ಮಿನ್ ಖಲ್ಕಿಕ ಫಮಿನ್ಕ ವಹ್ದಕ ಲಾ ಶರೀಕ ಲಕ, ಫಲಕಲ್ ಹಮ್ದು ವಲಕ ಶ್ಶುಕ್ರ್)",
	"KannadaTranslate":"ಓ ಅಲ್ಲಾಹ್! ನಾನು ಅಥವಾ ನಿನ್ನ ಸೃಷ್ಟಿಗಳಲ್ಲಿ ಸೇರಿದ ಯಾರಾದರೊಬ್ಬರು ಯಾವೆಲ್ಲ ಅನುಗ್ರಹಗಳೊಂದಿಗೆ ಬೆಳಗನ್ನು ಪ್ರವೇಶಿಸಿದ್ದಾರೋ ಅವೆಲ್ಲವೂ ಏಕೈಕನೂ ಸಹಭಾಗಿರಹಿತನೂ ಆಗಿರುವ ನಿನ್ನಿಂದ ಮಾತ್ರ. ಆದ್ದರಿಂದ ಸ್ತುತಿ ಮತ್ತು ಕೃತಜ್ಞತೆ ನಿನಗೆ ಮಾತ್ರ.",
	"Timing":"morning",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/81.mp3"
},
{
	"Id": 1,
	"ArabicText": "اللَّهُمَّ مَا أََمْسَ بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ، فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ",
	"EnglishText": ".Allahumma ma amsa bee min niAAmatin, aw bi-ahadin min khalqik, faminka wahdaka la shareeka lak, falakal-hamdu walakash-shukr.",
	"EnglishTranslate": "O Allah, what blessing I or any of Your creation have risen upon, is from You alone, without a partner, so for You is all praise and unto You all thanks.",
	"RomanUrduText": "Ae Allah! shaam ke waqt, mujh par ya teri makhlooq mein se kisi par jo bhi inaam huwa hai, woh teri hi taraf se hai, Tu akela hai, tera koi shareek nahi, pas tairay hi liye sab tareef hai aur tairay hi liye shukr hai.",
	"RomanUrduTranslate":"Ae Allah! shaam ke waqt, mujh par ya teri makhlooq mein se kisi par jo bhi inaam huwa hai, woh teri hi taraf se hai, Tu akela hai, tera koi shareek nahi, pas tairay hi liye sab tareef hai aur tairay hi liye shukr hai",
	"Timing":"evening",
	"KannadaText": "ಅಲ್ಲಾಹುಮ್ಮ ಮಾ ಅಮ್ಸಾ ಬೀ ಮಿನ್ ನಿಅïಮತಿನ್ ಅವ್ ಬಿಅಹದಿನ್ ಮಿನ್ ಖಲ್ಕಿಕ ಫಮಿನ್ಕ ವಹ್ದಕ ಲಾ ಶರೀಕ ಲಕ, ಫಲಕಲ್ ಹಮ್ದು ವಲಕ ಶ್ಶುಕ್ರ್",
	"KannadaTranslate":"ಓ ಅಲ್ಲಾಹ್! ನಾನು ಅಥವಾ ನಿನ್ನ ಸೃಷ್ಟಿಗಳಲ್ಲಿ ಸೇರಿದ ಯಾರಾದರೊಬ್ಬರು ಯಾವೆಲ್ಲ ಅನುಗ್ರಹಗಳೊಂದಿಗೆ ಸಂಜೆಯನ್ನು ಪ್ರವೇಶಿಸಿದ್ದಾರೋ ಅವೆಲ್ಲವೂ ಏಕೈಕನೂ ಸಹಭಾಗಿರಹಿತನೂ ಆಗಿರುವ ನಿನ್ನಿಂದ ಮಾತ್ರ. ಆದ್ದರಿಂದ ಸ್ತುತಿ ಮತ್ತು ಕೃತಜ್ಞತೆ ನಿನಗೆ ಮಾತ್ರ.",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/81.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لاَ إِلَهَ إِلاَّ أَنْتَ. اللَّهُمَّ  إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ، وَالفَقْرِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ القَبْرِ، لاَ إِلَهَ إِلاَّ أَنْتَ (ثلاثَ مرَّاتٍ)",
	"EnglishText": "Allahumma AAafinee fee badanee, allahumma AAafinee fee samAAee, allahumma AAafinee fee basaree, la ilaha illa ant.Allahumma innee aAAoothu bika minal-kufr, walfaqr, wa-aAAoothu bika min AAathabil-qabr, la ilaha illa ant .",
	"EnglishTranslate": "O Allah, grant my body health, O Allah, grant my hearing health, O Allah, grant my sight health.  None has the right to be worshipped except You.O Allah, I take refuge with You from disbelief and poverty, and I take refuge with You from the punishment of the grave.  None has the right to be worshipped except You.",
	"RomanUrduText": "Allahumma AAafinee fee badanee, allahumma AAafinee fee samAAee, allahumma AAafinee fee basaree, la ilaha illa ant.Allahumma innee aAAoothu bika minal-kufr, walfaqr, wa-aAAoothu bika min AAathabil-qabr, la ilaha illa ant .",
	"RomanUrduTranslate":"Ae Allah! mujhe mere badan mein aafiat day, ae Allah! mujhe mere kaanon mein aafiat day, ae Allah! mujhe meri aankhon mein aafiat day, tairay siwa koi mabood nahi. Ae Allah! yaqeenan mein kufr aur gurbat se teri pannah mein aata hun aur [ae Allah! Yaqeenan] mein azaab e qabr se teri panah mein aata hun, tairay siwa koi mabood nahi.",
	"KannadaText": "ಅಲ್ಲಾಹುಮ್ಮ ಆಫಿನೀ ಫೀ ಬದನೀ, ಅಲ್ಲಾಹುಮ್ಮ ಆಫಿನೀ ಫೀ ಸಮ್‍ಈ, ಅಲ್ಲಾಹುಮ್ಮ ಆಫಿನೀ ಫೀ ಬಸರೀ, ಲಾ ಇಲಾಹ ಇಲ್ಲಾ ಅನ್ತ್, ಅಲ್ಲಾಹುಮ್ಮ ಇನ್ನೀ ಅಊದು ಬಿಕ ಮಿನಲ್ ಕುಫ್ರಿ ವಲ್ ಫಕ್ರಿ, ವಅಊದು ಬಿಕ ಮಿನ ಅದಾಬಿಲ್ ಕಬ್ರಿ, ಲಾ ಇಲಾಹ ಇಲ್ಲಾ ಅನ್ತ್ (ಮೂರು ಸಲ)",
	"KannadaTranslate":"ಓ ಅಲ್ಲಾಹ್! ನನ್ನ ದೇಹದಲ್ಲಿ ನನಗೆ ಸೌಖ್ಯವನ್ನು ನೀಡು, ಓ ಅಲ್ಲಾಹ್! ನನ್ನ ಶ್ರವಣದಲ್ಲಿ ನನಗೆ ಸೌಖ್ಯವನ್ನು ನೀಡು, ಓ ಅಲ್ಲಾಹ್! ನನ್ನ ದೃಷ್ಟಿಯಲ್ಲಿ ನನಗೆ ಸೌಖ್ಯವನ್ನು ನೀಡು, ನೀನಲ್ಲದೆ ಆರಾಧನೆಗೆ ನೈಜ ಹಕ್ಕುದಾರರಾಗಿ ಅನ್ಯರಿಲ್ಲ. ಓ ಅಲ್ಲಾಹ್! ಸತ್ಯನಿμÉೀಧದಿಂದ ಮತ್ತು ದಾರಿದ್ರ್ಯದಿಂದ ನಾನು ನಿನ್ನೊಂದಿಗೆ ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ. ಮತ್ತು ಗೋರಿ ಶಿಕ್ಷೆಯಿಂದ ನಾನು ನಿನ್ನೊಂದಿಗೆ ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ. ನೀನಲ್ಲದೆ ಆರಾಧನೆಗೆ ನೈಜ ಹಕ್ಕುದಾರರಾಗಿ ಅನ್ಯರಿಲ್ಲ.",
	"Timing":"morningAndEvening",
	"Repeat": 3,
	"Audio": "http://www.hisnmuslim.com/audio/ar/82.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "حَسْبِيَ اللَّهُ لاَ إِلَهَ إِلاَّ هُوَ عَلَيهِ تَوَكَّلتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ (سَبْعَ مَرّاتٍ)",
	"EnglishText": "Hasbiyal-lahu la ilaha illa huwa, AAalayhi tawakkalt, wahuwa rabbul-AAarshil-AAatheem",
	"EnglishTranslate": "Allah is Sufficient for me, none has the right to be worshipped except Him, upon Him I rely and He is Lord of the exalted throne.",
	"RomanUrduText": "Hasbiyal-lahu la ilaha illa huwa, AAalayhi tawakkalt, wahuwa rabbul-AAarshil-AAatheem",
	"RomanUrduTranslate":"Mujhe Allah hi kaafi hai uskay siwa koi mabood nahi. usi par main ne bharosa kiya aur woh arsh azeem ka Rab hai.",
	"KannadaText": "ಹಸ್ಬಿಯಲ್ಲಾಹು ಲಾ ಇಲಾಹ ಇಲ್ಲಾ ಹುವ ಅಲೈಹಿ ತವಕ್ಕಲ್ತು ವಹುವ ರಬ್ಬುಲ್ ಅರ್ಶಿಲ್ ಅಝೀಮ್ (ಏಳು ಸಲ)",
	"KannadaTranslate":"ನನಗೆ ಅಲ್ಲಾಹು ಸಾಕು. ಅವನ ಹೊರತು ಆರಾಧನೆಗೆ ನೈಜ ಹಕ್ಕುದಾರರಾಗಿ ಅನ್ಯರಿಲ್ಲ. ಅವನು ಮಹಾ ಸಿಂಹಾಸನದ ಒಡೆಯ.",
	"Timing":"morningAndEvening",
	"Repeat": 7,
	"Audio": "http://www.hisnmuslim.com/audio/ar/83.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالآخِرَةِ، اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ: فِي دِينِي وَدُنْيَايَ وَأَهْلِي، وَمَالِي، اللَّهُمَّ اسْتُرْ عَوْرَاتِي، وَآمِنْ رَوْعَاتِي، اللَّهُمَّ احْفَظْنِي مِنْ بَينِ يَدَيَّ، وَمِنْ خَلْفِي، وَعَنْ يَمِينِي، وَعَنْ شِمَالِي، وَمِنْ فَوْقِي، وَأَعُوذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِي",
	"EnglishText": "Allahumma innee as-alukal-AAafwa walAAafiyah, fid-dunya wal-akhirah, allahumma innee as-alukal-AAafwa walAAafiyah fee deenee, wadunyaya wa-ahlee, wamalee, allahummas-tur AAawratee, wa-amin rawAAatee, allahummah-fathnee min bayni yaday, wamin khalfee, waAAan yameenee, waAAan shimalee, wamin fawqee, wa-aAAoothu biAAathamatika an oghtala min tahtee.",
	"EnglishTranslate": "O Allah, I ask You for pardon and well-being in this life and the next. O Allah, I ask You for pardon and well-being in my religious and worldly affairs, and my family and my wealth. O Allah, veil my weaknesses and set at ease my dismay. O Allah, preserve me from the front and from behind and on my right and on my left and from above, and I take refuge with You lest I be swallowed up by the earth.",
	"RomanUrduText": "Allahumma innee as-alukal-AAafwa walAAafiyah, fid-dunya wal-akhirah, allahumma innee as-alukal-AAafwa walAAafiyah fee deenee, wadunyaya wa-ahlee, wamalee, allahummas-tur AAawratee, wa-amin rawAAatee, allahummah-fathnee min bayni yaday, wamin khalfee, waAAan yameenee, waAAan shimalee, wamin fawqee, wa-aAAoothu biAAathamatika an oghtala min tahtee.",
	"RomanUrduTranslate":"[Ae Allah! be shak mein tujh se] duniya aur akhirat mein mafi aur aafiat ka sawal karta hun, ae Allah! be shak mein tujh se apne deen, apni duniya aur apne ahl o maal mein mafi aur aafiat ka sawal karta hun, Ae Allah! mere aibon par parda daal day aur meri ghabrahaton mein aman day. Ae Allah! Tu meri hifazat farma mere samnay se, mere peechay se mere dayen taraf se mere bayen taraf se aur mere oopar se. aur main teri azmat ke sath is baat se panah mangta hun ke nagahan apne neechay se halaak kiya jaaun",
	"KannadaText": "ಅಲ್ಲಾಹುಮ್ಮ ಇನ್ನೀ ಅಸ್‍ಅಲುಕಲ್ ಅಫ್ವ ವಲ್ ಆಫಿಯತ ಫಿದ್ದುನ್ಯಾ ವಲ್ ಆಖಿರತಿ, ಅಲ್ಲಾಹುಮ್ಮ ಇನ್ನೀ ಅಸ್‍ಅಲುಕಲ್ ಅಫ್ವ ವಲ್ ಆಫಿಯತ ಫೀ ದೀನೀ ವದುನ್ಯಾಯ ವಅಹ್ಲೀ ವಮಾಲೀ, ಅಲ್ಲಾಹುಮ್ಮಸ್ತುರ್ ಔರಾತೀ ವಆಮಿನ್ ರೌಆತೀ, ಅಲ್ಲಾಹುಮ್ಮಹ್ಫದ್‍ನೀ ಮಿನ್ ಬೈನಿ ಯದಯ್ಯ ವಮಿನ್ ಖಲ್ಫೀ ವಅನ್ ಯಮೀನೀ ವಅನ್ ಶಿಮಾಲೀ ವಮಿನ್ ಫೌಕೀ, ವಅಊದು ಬಿಅದಮತಿಕ ಅನ್ ಉಗ್ತಾಲ ಮಿನ್ ತಹ್ತೀ ",
	"KannadaTranslate":"ಓ ಅಲ್ಲಾಹ್! ಇಹಲೋಕದಲ್ಲೂ ಪರಲೋಕದಲ್ಲೂ ನನಗೆ ಕ್ಷಮೆ ಮತ್ತು ಸೌಖ್ಯ ನೀಡಬೇಕೆಂದು ನಾನು ನಿನ್ನೊಂದಿಗೆ ಬೇಡುತ್ತಿದ್ದೇನೆ. ಓ ಅಲ್ಲಾಹ್! ನನ್ನ ಧರ್ಮದಲ್ಲಿ, ನನ್ನ ಐಹಿಕ ಜೀವನದಲ್ಲಿ, ನನ್ನ ಕುಟುಂಬದಲ್ಲಿ, ನನ್ನ ಸಂಪತ್ತಿನಲ್ಲಿ ನನಗೆ ಕ್ಷಮೆ ಮತ್ತು ಸೌಖ್ಯ ನೀಡಬೇಕೆಂದು ನಾನು ನಿನ್ನೊಂದಿಗೆ ಬೇಡುತ್ತಿದ್ದೇನೆ. ಓ ಅಲ್ಲಾಹ್! ನನ್ನ ಕೊರತೆಗಳನ್ನು ಮರೆಮಾಚು, ನನ್ನ ಭಯವನ್ನು ನೀಗಿಸು. ಓ ಅಲ್ಲಾಹ್! ನನ್ನ ಮುಂದಿನಿಂದಲೂ, ನನ್ನ ಹಿಂದಿನಿಂದಲೂ, ನನ್ನ ಬಲಭಾಗದಿಂದಲೂ, ನನ್ನ ಎಡಭಾಗದಿಂದಲೂ, ನನ್ನ ಮೇಲ್ಭಾಗದಿಂದಲೂ ನನ್ನನ್ನು ಸಂರಕ್ಷಿಸು ಮತ್ತು ಕೆಳಭಾಗದಿಂದ ನನ್ನನ್ನು ವಂಚಿಸಲ್ಪಡುವುದರ ಬಗ್ಗೆ ನಿನ್ನ ಔನ್ನತ್ಯದೊಂದಿಗೆ ನಾನು ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ.",
	"Timing":"morningAndEvening",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/84.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "اللَّهُمَّ عَالِمَ الغَيْبِ وَالشَّهَادَةِ فَاطِرَ السَّمَوَاتِ وَالْأَرْضِ، رَبَّ كُلِّ شَيْءٍ وَمَلِيكَهُ، أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ أَنْتَ، أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي، وَمِنْ شَرِّ الشَّيْطانِ وَشَرَكِهِ، وَأَنْ أَقْتَرِفَ عَلَى  نَفْسِي سُوءاً، أَوْ أَجُرَّهُ إِلَى مُسْلِمٍ",
	"EnglishText": "Allahumma AAalimal-ghaybi washshahadah, fatiras-samawati wal-ard, rabba kulli shayin wamaleekah, ashhadu an la ilaha illa ant, aAAoothu bika min sharri nafsee wamin sharrish-shaytani washirkih, waan aqtarifa AAala nafsee soo-an aw ajurrahu ila muslim.",
	"EnglishTranslate": "O Allah, Knower of the unseen and the seen, Creator of the heavens and the Earth, Lord and Sovereign of all things, I bear witness that none has the right to be worshipped except You. I take refuge in You from the evil of my soul and from the evil and shirk of the devil, and from committing wrong against my soul or bringing such upon another Muslim.",
	"RomanUrduText": "Allahumma AAalimal-ghaybi washshahadah, fatiras-samawati wal-ard, rabba kulli shayin wamaleekah, ashhadu an la ilaha illa ant, aAAoothu bika min sharri nafsee wamin sharrish-shaytani washirkih, waan aqtarifa AAala nafsee soo-an aw ajurrahu ila muslim.",
	"RomanUrduTranslate":"Ae Allah! ae asmano aur zameen ke paida karne walay! ae gayab o haazir ko jannay walay, tairay ilawa koi mabood nahi, har cheez ke Rab aur us ke maalik, mein teri panah mein aata hun apne nafs ke shar se aur shaytan ke shar se aur is ke shirk se aur is baat se ke apne hi khilaaf kisi buraiee ka irtikaab karoon ya usay kisi musalman ki taraf khench laaun",
	"KannadaText": "ಅಲ್ಲಾಹುಮ್ಮ ಆಲಿಮಲ್ ಗೈಬಿ ವಶ್ಶಹಾದತಿ, ಫಾತಿರ ಸ್ಸಮಾವಾತಿ ವಲ್ ಅರ್ದಿ, ರಬ್ಬ ಕುಲ್ಲಿ ಶೈಇನ್ ವಮಲೀಕಹೂ, ಅಶ್‍ಹದು ಅನ್ ಲಾ ಇಲಾಹ ಇಲ್ಲಾ ಅನ್ತ, ಅಊದು ಬಿಕ ಮಿನ್ ಶರ್ರಿ ನಫ್ಸೀ ವಶರ್ರಿ ಶ್ಶೈತಾನಿ ವಶಿರ್ಕಿಹ್, ವಅನ್ ಅಕ್‍ತರಿಫ ಅಲಾ ನಫ್ಸೀ ಸೂಅನ್, ಅವ್ ಅಜುರ್ರಹು ಇಲಾ ಮುಸ್ಲಿಮ್",
	"KannadaTranslate":"ಓ ಅಲ್ಲಾಹ್! ದೃಶ್ಯ ಮತ್ತು ಅದೃಶ್ಯಗಳನ್ನು ಅರಿತವನೇ! ಆಕಾಶಗಳ ಮತ್ತು ಭೂಮಿಯ ಸೃಷ್ಟಿಕರ್ತನೇ! ಸರ್ವ ವಸ್ತುಗಳ ರಬ್ಬ್ ಮತ್ತು ಅಧಿಪತಿಯೇ! ನೀನಲ್ಲದೆ ಅನ್ಯ ಸತ್ಯ ಆರಾಧ್ಯರಿಲ್ಲ. ನನ್ನ ದೇಹದ ಕೆಡುಕಿನಿಂದ, ಶೈತಾನನ ಕೆಡುಕಿನಿಂದ ಮತ್ತು ಅವನ ಸಹಭಾಗಿತ್ವದಿಂದ ನಾನು ನಿನ್ನೊಂದಿಗೆ ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ. ಮತ್ತು ನಾನು ನನ್ನ ಶರೀರದ ಮೇಲೆ ಅನ್ಯಾಯವೆಸಗುವುದರಿಂದ ಮತ್ತು ಅದನ್ನು ಮುಸ್ಲಿಮನಿಗೆ ಮಾಡುವುದರಿಂದ ನಾನು ನಿನ್ನೊಂದಿಗೆ ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ.",
	"Timing":"morningAndEvening",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/85.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "بِسْمِ اللَّهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلاَ فِي السّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ (ثلاثَ مرَّاتٍ)",
	"EnglishText": "Bismil-lahil-lathee la yadurru maAAas-mihi shay-on fil-ardi wala fis-sama-i wahuwas-sameeAAul-AAaleem.",
	"EnglishTranslate": "In the name of Allah with whose name nothing is harmed on earth nor in the heavens and He is The All-Seeing, The All-Knowing.",
	"RomanUrduText": "Bismil-lahil-lathee la yadurru maAAas-mihi shay-on fil-ardi wala fis-sama-i wahuwas-sameeAAul-AAaleem.",
	"RomanUrduTranslate":"Allah ke naam ke sath jis ke naam ki barkat se koi cheez nuqsaan nahi pohncha sakti, zameen ki ho ya asmano ki aur woh khoob sunney wala, khoob jan-ne wala hai",
	"KannadaText": "ಬಿಸ್ಮಿಲ್ಲಾಹಿಲ್ಲದೀ ಲಾ ಯದುರ್ರು ಮಅಸ್ಮಿಹೀ ಶೈಉನ್ ಫಿಲ್ ಅರ್ದಿ ವಲಾ ಫಿ ಸ್ಸಮಾಇ ವಹುವ ಸ್ಸಮೀಉಲ್ ಅಲೀಮ್ (ಮೂರು ಸಲ)",
	"KannadaTranslate":"ಭೂಮಿಯಲ್ಲಿ ಮತ್ತು ಆಕಾಶದಲ್ಲಿ ಯಾರ ನಾಮದಿಂದ ಯಾವುದೇ ವಸ್ತುವೂ ತೊಂದರೆಯನ್ನುಂಟು ಮಾಡಲಾರದೋ, ಆ ಅಲ್ಲಾಹನ ನಾಮದಿಂದ. ಅವನು ಎಲ್ಲವನ್ನೂ ಆಲಿಸುವವನೂ ಅರಿವುಳ್ಳವನೂ ಆಗಿದ್ದಾನೆ.",
	"Timing":"morningAndEvening",
	"Repeat": 3,
	"Audio": "http://www.hisnmuslim.com/audio/ar/86.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "رَضِيتُ بِاللَّهِ رَبَّاً، وَبِالْإِسْلاَمِ دِيناً، وَبِمُحَمَّدٍ صلى الله عليه وسلم نَبِيّاً (ثلاثَ مرَّاتٍ)",
	"EnglishText": "Radeetu billahi rabban wabil-islami deenan wabiMuhammadin  nabiyya. ",
	"EnglishTranslate": "I am pleased with Allah as a Lord, and Islam as a religion and Muhammad  as a Prophet.",
	"RomanUrduText": "Radeetu billahi rabban wabil-islami deenan wabiMuhammadin  nabiyya. ",
	"RomanUrduTranslate":"Mein Allah ke sath (us ke) Rab honay par raazi ho gaya, Islam ke sath (us ke) deen honay par aur Mohammad ke sath (un ke) Nabi honay par.",
	"KannadaText": "ರದೀತು ಬಿಲ್ಲಾಹಿ ರಬ್ಬನ್, ವಬಿಲ್ ಇಸ್ಲಾಮಿ ದೀನನ್, ವಬಿಮುಹಮ್ಮದಿನ್ ರಸೂಲÁ (ಮೂರು ಸಲ)",
	"KannadaTranslate":"ರಬ್ಬ್ ಆಗಿ ಅಲ್ಲಾಹನನ್ನು, ಧರ್ಮವಾಗಿ ಇಸ್ಲಾಮನ್ನು ಮತ್ತು ರಸೂಲರಾಗಿ ಮುಹಮ್ಮದ್‍ರನ್ನು ನಾನು ತೃಪ್ತಿಪಟ್ಟಿದ್ದೇನೆ.",
	"Timing":"morningAndEvening",
	"Repeat": 3,
	"Audio": "http://www.hisnmuslim.com/audio/ar/87.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغيثُ أَصْلِحْ لِي شَأْنِيَ كُلَّهُ وَلاَ تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ",
	"EnglishText": "Ya hayyu ya qayyoom, birahmatika astagheeth, aslih lee sha/nee kullah, wala takilnee ila nafsee tarfata AAayn.",
	"EnglishTranslate": "O Ever Living, O Self-Subsisting and Supporter of all, by Your mercy I seek assistance, rectify for me all of my affairs and do not leave me to myself, even for the blink of an eye.",
	"RomanUrduText": "Ya hayyu ya qayyoom, birahmatika astagheeth, aslih lee sha/nee kullah, wala takilnee ila nafsee tarfata AAayn.",
	"RomanUrduTranslate":"Ae zindah javed! ae qaim o daaim! mein teri hi rehmat ke zariye se madad talab karta hun, Tu mera kaam sanwaar day aur aankh jhapkane ke barabar bhi mujhe mere nafs ke supurd na karna",
	"KannadaText": "ಯಾ ಹಯ್ಯು ಯಾ ಕಯ್ಯೂಮು ಬಿರಹ್ಮತಿಕ ಅಸ್ತಗೀಸು ಅಸ್ಲಿಹ್ ಲೀ ಶಅïನೀ ಕುಲ್ಲಹೂ ವಲಾ ತಕಿಲ್‍ನೀ ಇಲಾ ನಫ್ಸೀ ತರ್‍ಫತ ಐನ್",
	"KannadaTranslate":"ಓ ನಿರಂತರವಾಗಿ ಬದುಕಿರುವವನೇ! ಓ ಸರ್ವವನ್ನೂ ನಿಯಂತ್ರಿಸುವವನೇ! ನಿನ್ನ ದಯೆಯೊಂದಿಗೆ ನಾನು ಸಹಾಯ ಬೇಡುತ್ತಿದ್ದೇನೆ, ನನ್ನ ಎಲ್ಲಾ ವಿಷಯಗಳನ್ನೂ ನನಗೆ ಉತ್ತಮವಾಗಿಸಿ ಕೊಡು, ನನ್ನನ್ನು ಸ್ವತಃ ನನ್ನ ಮೇಲೆ ಒಂದು ಕ್ಷಣ ಕೂಡ ಅವಲಂಬಿಸುವಂತೆ ಮಾಡದಿರು.",
	"Timing":"morningAndEvening",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/88.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْماً نَافِعاً، وَرِزْقاً طَيِّباً، وَعَمَلاً مُتَقَبَّلاً",
	"EnglishText": "Allahumma innee as-aluka AAilman nafiAAan, warizqan tayyiban, waAAamalan mutaqabbalan.",
	"KannadaText": "ಅಲ್ಲಾಹುಮ್ಮ ಇನ್ನೀ ಅಸ್‌ಅಲುಕ ಇಲ್ಮನ್ ನಾಫಿಅನ್, ವರಿಝ್ಕನ್ ತಯ್ಯಿಬನ್, ವಅಮಲನ್ ಮುತಕಬ್ಬಲಾ) (ಬೆಳಗ್ಗೆ)",
	"RomanUrduText": "Allahumma innee as-aluka AAilman nafiAAan, warizqan tayyiban, waAAamalan mutaqabbalan.",
	"RomanUrduTranslate":"Ae Allah! be shak mein tujh se nafa dainay walay ilm ka sawal karta hun aur pakeeza rizq ka aur aisay amal ka jo qubool kar liya jaye.",
	"KannadaTranslate":"ಓ ಅಲ್ಲಾಹ್! ನಾನು ನಿನ್ನೊಂದಿಗೆ ಪ್ರಯೋಜನಕರ ಜ್ಞಾನವನ್ನು, ಉತ್ತಮವಾದ ಅನ್ನಾಧಾರವನ್ನು ಮತ್ತು ಸ್ವೀಕೃತವಾದ ಕರ್ಮಗಳನ್ನು ಬೇಡುತ್ತಿದ್ದೇನೆ.",
	"EnglishTranslate": "O Allah, I ask You for knowledge which is beneficial and sustenance which is good, and deeds which are acceptable.",
	"Timing":"morning",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/95.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ: عَدَدَ خَلْقِهِ، وَرِضَا نَفْسِهِ، وَزِنَةَ عَرْشِهِ، وَمِدَادَ كَلِمَاتِهِ (ثلاثَ مرَّاتٍ إذا أصبحَ)",
	"EnglishText": "Subhanal-lahi wabihamdih, AAadada khalqihi warida nafsih, wazinata AAarshih, wamidada kalimatih.",
	"KannadaText": "ಸುಬ್‍ಹಾನಲ್ಲಾಹಿ ವಬಿಹಮ್ದಿಹೀ ಅದದ ಖಲ್ಕಿಹೀ ವರಿದಾ ನಫ್ಸಿಹೀ ವಝಿನತ ಅರ್ಶಿಹೀ ವಮಿದಾದ ಕಲಿಮಾತಿಹೀ (ಬೆಳಗ್ಗೆ ಮೂರು ಸಲ)",
	"RomanUrduText": "Subhanal-lahi wabihamdih, AAadada khalqihi warida nafsih, wazinata AAarshih, wamidada kalimatih.",
	"RomanUrduTranslate":"",
	"KannadaTranslate":"ಅಲ್ಲಾಹನ ಪರಿಪಾವನೆತೆಯನ್ನು ಅವನ ತೃಪ್ತಿಯೊಂದಿಗೆ ಕೊಂಡಾಡುತ್ತೇನೆ, ಅವನ ಸೃಷ್ಟಿಗಳ ಸಂಖ್ಯೆಯಷ್ಟು, ಅವನ ಮನಸ್ಸಿನ ತೃಪ್ತಿಯಷ್ಟು, ಅವನ ಸಿಂಹಾಸನದ ತೂಕದಷ್ಟು ಮತ್ತು ಅವನ ವಚನಗಳ ಸಂಖ್ಯೆಯಷ್ಟು.",
	"EnglishTranslate": "How perfect Allah is and I praise Him by the number of His creation and His pleasure, and by the weight of His throne, and the ink of His words.",
	"Timing":"morning",
	"Repeat": 3,
	"Audio": "http://www.hisnmuslim.com/audio/ar/94.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ رَبِّ الْعَالَمِينَ، اللَّهُـمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذَا الْيَوْمِ:فَتْحَهُ، وَنَصْرَهُ، وَنورَهُ، وَبَرَكَتَهُ، وَهُدَاهُ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِيهِ وَشَرِّ مَا بَعْدَهُ",
	"EnglishText": "Asbahna wa-asbahal-mulku lillahi rabbil-AAalameen, allahumma innee as-aluka khayra hathal-yawm, fat-hahu, wanasrahu, wanoorahu, wabarakatahu, wahudahu, wa-aAAoothu bika min sharri ma feehi, washarri ma baAAdah.",
	"EnglishTranslate": "We have reached the morning and at this very time all sovereignty belongs to Allah, Lord of the worlds. O Allah, I ask You for the good of this day, its triumphs and its victories, its light and its blessings and its guidance, and I take refuge in You from the evil of this day and the evil that follows it.",
	"RomanUrduText": "Asbahna wa-asbahal-mulku lillahi rabbil-AAalameen, allahumma innee as-aluka khayra hathal-yawm, fat-hahu, wanasrahu, wanoorahu, wabarakatahu, wahudahu, wa-aAAoothu bika min sharri ma feehi, washarri ma baAAdah.",
	"RomanUrduTranslate":"Ham ne subah ki, aur Allah Rab alameen ke saaray mulk ne subah ki. ae Allah! mein tujh se is din132 ki behtari mangta hun aur is ki fatah o nusrat is ka noor is ki barkat aur is ki hidaayat aur mein is din ke shar aur is ke baad ke shar se teri panah chahta hun.",
	"KannadaText": "ಅಸ್ಬಹ್‍ನಾ ವಅಸ್ಬಹಲ್ ಮುಲ್ಕು ಲಿಲ್ಲಾಹಿ ರಬ್ಬಿಲ್ ಆಲಮೀನ್. ಅಲ್ಲಾಹುಮ್ಮ ಇನ್ನೀ ಅಸ್‍ಅಲುಕ ಖೈರ ಹಾದಲ್ ಯೌಮಿ ಫತ್‍ಹಹೂ ವನಸ್ರಹೂ ವನೂರಹೂ ವಬರಕತಹೂ ವಹುದಾಹು, ವಅಊದು ಬಿಕ ಮಿನ್ ಶರ್ರಿ ಮಾ ಫೀಹಿ ವಶರ್ರಿ ಮಾ ಬಅïದಹ್)",
	"KannadaTranslate":"ನಾವು ಬೆಳಗನ್ನು ಪ್ರವೇಶಿಸಿದೆವು ಮತ್ತು ಸರ್ವಲೋಕಗಳ ಒಡೆಯನಾದ ಅಲ್ಲಾಹನ ಸಂಪೂರ್ಣ ಆಧಿಪತ್ಯವು ಬೆಳಗನ್ನು ಪ್ರವೇಶಿಸಿತು. ಓ ಅಲ್ಲಾಹು ನಾನು ಈ ದಿನದ ಒಳಿತನ್ನು, ಜಯವನ್ನು, ಸಹಾಯವನ್ನು, ಬೆಳಕನ್ನು, ಸಮೃದ್ಧಿಯನ್ನು ಮತ್ತು ಮಾರ್ಗದರ್ಶನವನ್ನು ಬೇಡುತ್ತಿದ್ದೇನೆ. ಈ ದಿನದಲ್ಲಿರುವ ಕೆಡುಕಿನಿಂದ ಮತ್ತು ಇದರ ನಂತರದ ದಿನಗಳಲ್ಲಿರುವ ಕೆಡುಕಿನಿಂದ ನಾನು ನಿನ್ನೊಂದಿಗೆ ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ.",
	"Timing":"morningAndEvening",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/89.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ رَبِّ الْعَالَمِينَ، اللَّهُـمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذَا الْيَوْمِ:فَتْحَهُ، وَنَصْرَهُ، وَنورَهُ، وَبَرَكَتَهُ، وَهُدَاهُ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِيهِ وَشَرِّ مَا بَعْدَهُ",
	"EnglishText": "Amsayna wa-amsal-mulku lillahi rabbil-AAalameen, allahumma innee as-aluka khayra hathihil-laylah, fat-haha, wanasraha, wanooraha, wabarakataha, wahudaha, wa-aAAoothu bika min sharri ma feeha washarri ma baAAdaha.",
	"EnglishTranslate": "We have reached the evening and at this very time all sovereignty belongs to Allah, Lord of the worlds. O Allah, I ask You for the good of tonight, its triumphs and its victories, its light and its blessings and its guidance, and I take refuge in You from the evil of tonight and the evil that follows it.",
	"RomanUrduText": "Amsayna wa-amsal-mulku lillahi rabbil-AAalameen, allahumma innee as-aluka khayra hathihil-laylah, fat-haha, wanasraha, wanooraha, wabarakataha, wahudaha, wa-aAAoothu bika min sharri ma feeha washarri ma baAAdaha.",
	"RomanUrduTranslate":"Ham ne shaam ki, aur Allah Rab alameen ke saaray mulk ne shaam ki. ae Allah! mein tujh se is raat ki behtari mangta hun aur is ki fatah o nusrat is ka noor is ki barkat aur is ki hidaayat aur mein is raat ke shar aur is ke baad ke shar se teri panah chahta hun",
	"KannadaText": "ಅಮ್ಸಯ್ನಾ ವ ಅಮ್ಸಲ್ಮುಲ್ಕು ಲಿಲ್ಲಾಹಿ ರಬ್ಬಿಲ್ ಆಲಮೀನ್. ಅಲ್ಲಾಹುಮ್ಮ ಇನ್ನೀ ಅಸ್‍ಅಲುಕ ಖೈರ ಹಾದಿಹಿ ಲ್ಲೆöÊಲತಿ ಫತ್‍ಹಹಾ ವನಸ್ರಹಾ ವನೂರಹಾ ವಬರಕತಹಾ ವಹುದಾಹಾ, ವಅಊದು ಬಿಕ ಮಿನ್ ಶರ್ರಿ ಮಾ ಫೀಹಾ ವಶರ್ರಿ ಮಾ ಬಅïದಹಾ)",
	"KannadaTranslate":"ನಾವು ಸಂಜೆಯನ್ನು ಪ್ರವೇಶಿಸಿದೆವು ಮತ್ತು ಸರ್ವಲೋಕಗಳ ಒಡೆಯನಾದ ಅಲ್ಲಾಹನ ಸಂಪೂರ್ಣ ಆಧಿಪತ್ಯವು ಸಂಜೆಯನ್ನು ಪ್ರವೇಶಿಸಿತು. ಓ ಅಲ್ಲಾಹು ನಾನು ಈ ರಾತ್ರಿಯ ಒಳಿತನ್ನು, ಜಯವನ್ನು, ಸಹಾಯವನ್ನು, ಬೆಳಕನ್ನು, ಸಮೃದ್ಧಿಯನ್ನು ಮತ್ತು ಮಾರ್ಗದರ್ಶನವನ್ನು ಬೇಡುತ್ತಿದ್ದೇನೆ. ಈ ದಿನದಲ್ಲಿರುವ ಕೆಡುಕಿನಿಂದ ಮತ್ತು ಇದರ ನಂತರದ ದಿನಗಳಲ್ಲಿರುವ ಕೆಡುಕಿನಿಂದ ನಾನು ನಿನ್ನೊಂದಿಗೆ ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ.",
	"Timing":"morningAndEvening",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/89.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "أَصْبَحْنا عَلَى فِطْرَةِ الْإِسْلاَمِ، وَعَلَى كَلِمَةِ الْإِخْلاَصِ، وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ صلى الله عليه وسلم، وَعَلَى مِلَّةِ أَبِينَا إِبْرَاهِيمَ، حَنِيفاً مُسْلِماً وَمَا كَانَ مِنَ الْمُشرِكِينَ",
	"EnglishText": "Asbahna AAala fitratil-islam, waAAala kalimatil-ikhlas, waAAala deeni nabiyyina Muhammad  waAAala millati abeena Ibraheem, haneefan musliman wama kana minal-mushrikeen.",
	"EnglishTranslate": "We rise upon the fitrah of Islam, and the word of pure faith, and upon the religion of our Prophet Muhammad  and the religion of our forefather Ibraheem, who was a Muslim and of true faith and was not of those who associate others with Allah.",
	"RomanUrduText": "Asbahna AAala fitratil-islam, waAAala kalimatil-ikhlas, waAAala deeni nabiyyina Muhammad  waAAala millati abeena Ibraheem, haneefan musliman wama kana minal-mushrikeen.",
	"RomanUrduTranslate":"Ham ne fitrat e Islam, kalima e ikhlaas, aur apne Nabi hazrat Mohammad                                                                                                       ke deen aur apne baap hazrat Ibrahim   jo yak rukh (aur) farmaan bardaar thay, ki millat par subah ki aur woh mushrikon mein nahi thay",
	"KannadaText": "ಅಸ್ಬಹ್‍ನಾ ಅಲಾ ಫಿತ್ರತಿಲ್ ಇಸ್ಲಾಮಿ, ವಕಲಿಮತಿಲ್ ಇಖ್ಲಾಸಿ, ವದೀನಿ ನಬಿಯ್ಯಿನಾ ಮುಹಮ್ಮದಿನ್ ಸಲ್ಲಲ್ಲಾಹು ಅಲೈಹಿ ವಸಲ್ಲಮ, ವಮಿಲ್ಲತಿ ಅಬೀನಾ ಇಬ್ರಾಹೀಮ ಹನೀಫನ್ ವಮಾ ಕಾನ ಮಿನಲ್ ಮುಶ್ರಿಕೀನ್ ",
	"KannadaTranslate":"ಇಸ್ಲಾಮಿನ ಪ್ರಕೃತಿಯಲ್ಲಿ, ನಿಷ್ಕಳಂಕವಾದ ವಚನದೊಂದಿಗೆ, ನಮ್ಮ ಪ್ರವಾದಿಯಾದ ಮುಹಮ್ಮದ್‍ರವರ ಧರ್ಮದಲ್ಲಿ ಮತ್ತು ಋಜುಮನಸ್ಕರೂ ಬಹುದೇವವಿಶ್ವಾಸಿಗಳಲ್ಲಿ ಒಳಪಡದವರೂ ಆಗಿರುವ ಇಬ್ರಾಹೀಮ್‍ರವರ ಮಾರ್ಗದಲ್ಲಿ ನಾವು ಬೆಳಗನ್ನು ಪ್ರವೇಶಿಸಿದೆವು.",
	"Timing":"morning",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/90.mp3"
},
	{
	"Id": 1,
	"ArabicText": "أَصْبَحْنا عَلَى فِطْرَةِ الْإِسْلاَمِ، وَعَلَى كَلِمَةِ الْإِخْلاَصِ، وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ صلى الله عليه وسلم، وَعَلَى مِلَّةِ أَبِينَا إِبْرَاهِيمَ، حَنِيفاً مُسْلِماً وَمَا كَانَ مِنَ الْمُشرِكِينَ",
	"EnglishText": "amsayna AAala fitratil-islam, waAAala kalimatil-ikhlas, waAAala deeni nabiyyina Muhammad  waAAala millati abeena Ibraheem, haneefan musliman wama kana minal-mushrikeen.",
	"EnglishTranslate": "We rise upon the fitrah of Islam, and the word of pure faith, and upon the religion of our Prophet Muhammad  and the religion of our forefather Ibraheem, who was a Muslim and of true faith and was not of those who associate others with Allah.",
	"RomanUrduText": "amsayna AAala fitratil-islam, waAAala kalimatil-ikhlas, waAAala deeni nabiyyina Muhammad  waAAala millati abeena Ibraheem, haneefan musliman wama kana minal-mushrikeen.",
	"RomanUrduTranslate":"",
	"KannadaText": "ಅಮ್ಸಯ್ನಾ ಅಲಾ ಫಿತ್ರತಿಲ್ ಇಸ್ಲಾಮಿ, ವಕಲಿಮತಿಲ್ ಇಖ್ಲಾಸಿ, ವದೀನಿ ನಬಿಯ್ಯಿನಾ ಮುಹಮ್ಮದಿನ್ ಸಲ್ಲಲ್ಲಾಹು ಅಲೈಹಿ ವಸಲ್ಲಮ, ವಮಿಲ್ಲತಿ ಅಬೀನಾ ಇಬ್ರಾಹೀಮ ಹನೀಫನ್ ವಮಾ ಕಾನ ಮಿನಲ್ ಮುಶ್ರಿಕೀನ್ ",
	"KannadaTranslate":"ಇಸ್ಲಾಮಿನ ಪ್ರಕೃತಿಯಲ್ಲಿ, ನಿಷ್ಕಳಂಕವಾದ ವಚನದೊಂದಿಗೆ, ನಮ್ಮ ಪ್ರವಾದಿಯಾದ ಮುಹಮ್ಮದ್‍ರವರ ಧರ್ಮದಲ್ಲಿ ಮತ್ತು ಋಜುಮನಸ್ಕರೂ ಬಹುದೇವವಿಶ್ವಾಸಿಗಳಲ್ಲಿ ಒಳಪಡದವರೂ ಆಗಿರುವ ಇಬ್ರಾಹೀಮ್‍ರವರ ಮಾರ್ಗದಲ್ಲಿ ನಾವು ಸಂಜೆಯನ್ನು ಪ್ರವೇಶಿಸಿದೆವು.",
	"Timing":"evening",
	"Repeat": 1,
	"Audio": "http://www.hisnmuslim.com/audio/ar/90.mp3"
},
	{
	"Id": 1,
	"ArabicText": "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ (مائة مرَّةٍ)",
	"EnglishText": "Subhanal-lahi wabihamdih",
	"EnglishTranslate": "How perfect Allah is and I praise Him",
	"RomanUrduText": "Subhanal-lahi wabihamdih",
	"RomanUrduTranslate":"Mein Allah ki pakizgee bayan karta hun us ki tareef ke sath",
	"KannadaText": "ಸುಬ್‍ಹಾನಲ್ಲಾಹಿ ವಬಿಹಮ್ದಿಹ್ (ನೂರು ಬಾರಿ)",
	"KannadaTranslate":"ಅಲ್ಲಾಹನ ಪರಿಪಾವನತೆಯನ್ನು ಕೊಂಡಾಡುತ್ತೇನೆ ಮತ್ತು ಅವನ ಸ್ತುತಿಯೊಂದಿಗೆ.",
	"Timing":"morningAndEvening",
	"Repeat": 100,
	"Audio": "http://www.hisnmuslim.com/audio/ar/91.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ (عشرَ مرَّات) ، أَوْ (مرَّةً واحدةً عندَ الكَسَلِ)",
	"EnglishText": "La ilaha illal-lah, wahdahu la shareeka lah, lahul-mulku walahul-hamd, wahuwa AAala kulli shay-in qadeer.  [ten times or once if lazy]",
	"EnglishTranslate": "None has the right to be worshipped except Allah, alone, without partner, to Him belongs all sovereignty and praise, and He is over all things omnipotent.",
	"RomanUrduText": "La ilaha illal-lah, wahdahu la shareeka lah, lahul-mulku walahul-hamd, wahuwa AAala kulli shay-in qadeer.  [ten times or once if lazy]",
	"RomanUrduTranslate":"Allah ke ilawa koi mabood nahi woh akela hai, us ka koi shareek nahi, usi ki badshahat hai aur usi ki tareef hai aur woh har cheez par kaamil qudrat rakhtahai",
	"KannadaText": "ಲಾ ಇಲಾಹ ಇಲ್ಲಲ್ಲಾಹು ವಹ್ದಹೂ ಲಾ ಶರೀಕ ಲಹೂ, ಲಹುಲ್ ಮುಲ್ಕು ವಲಹುಲ್ ಹಮ್ದು, ವಹುವ ಅಲಾ ಕುಲ್ಲಿ ಶೈಇನ್ ಕದೀರ್ (ಬೆಳಿಗ್ಗೆ ನೂರು ಸಲ)",
	"KannadaTranslate":"ಅಲ್ಲಾಹನ ಹೊರತು ಆರಾಧನೆಗೆ ನೈಜ ಹಕ್ಕುದಾರರಾಗಿ ಅನ್ಯರಿಲ್ಲ, ಅವನು ಏಕೈಕನೂ ಸಹಭಾಗಿರಹಿತನೂ ಆಗಿರುವನು, ಆಧಿಪತ್ಯವು ಅವನದ್ದು ಮತ್ತು ಸ್ತುತಿಯು ಅವನಿಗೆ, ಅವನು ಎಲ್ಲಾ ವಿಷಯಗಳಲ್ಲೂ ಸಾಮರ್ಥ್ಯವುಳ್ಳವನು.",
	"Timing":"morningAndEvening",
	"Repeat": 10,
	"Audio": "http://www.hisnmuslim.com/audio/ar/92.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "لاَ إِلَهَ إِلاَّ اللَّهُ، وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ (مائةَ مرَّةٍ إذا أصبحَ)",
	"EnglishText": "La ilaha illal-lah, wahdahu la shareeka lah, lahul-mulku walahul-hamd, wahuwa AAala kulli shay-in qadeer. ",
	"EnglishTranslate": "None has the right to be worshipped except Allah, alone, without partner, to Him belongs all sovereignty and praise, and He is over all things omnipotent.",
	"RomanUrduText": "La ilaha illal-lah, wahdahu la shareeka lah, lahul-mulku walahul-hamd, wahuwa AAala kulli shay-in qadeer. ",
	"RomanUrduTranslate":"Allah ke ilawa koi mabood nahi woh akela hai, us ka koi shareek nahi, usi ki badshahat hai aur usi ki tareef hai aur woh har cheez par kaamil qudrat rakhtahai",
	"KannadaText": "ಲಾ ಇಲಾಹ ಇಲ್ಲಲ್ಲಾಹು ವಹ್ದಹೂ ಲಾ ಶರೀಕ ಲಹೂ, ಲಹುಲ್ ಮುಲ್ಕು ವಲಹುಲ್ ಹಮ್ದು, ವಹುವ ಅಲಾ ಕುಲ್ಲಿ ಶೈಇನ್ ಕದೀರ್ (ಬೆಳಿಗ್ಗೆ ನೂರು ಸಲ)",
	"KannadaTranslate":"ಅಲ್ಲಾಹನ ಹೊರತು ಆರಾಧನೆಗೆ ನೈಜ ಹಕ್ಕುದಾರರಾಗಿ ಅನ್ಯರಿಲ್ಲ, ಅವನು ಏಕೈಕನೂ ಸಹಭಾಗಿರಹಿತನೂ ಆಗಿರುವನು, ಆಧಿಪತ್ಯವು ಅವನದ್ದು ಮತ್ತು ಸ್ತುತಿಯು ಅವನಿಗೆ, ಅವನು ಎಲ್ಲಾ ವಿಷಯಗಳಲ್ಲೂ ಸಾಮರ್ಥ್ಯವುಳ್ಳವನು.",
	"Timing":"morningAndEvening",
	"Repeat": 100,
	"Audio": "http://www.hisnmuslim.com/audio/ar/93.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ (مِائَةَ مَرَّةٍ فِي الْيَوْمِ)",
	"EnglishText": "Astaghfirullaaha wa 'atoobu 'ilayhi[one hundred times a day]",
	"EnglishTranslate": "I seek Allaah’s forgiveness and I turn to Him in repentance.",
	"RomanUrduText": "Astaghfirullaaha wa 'atoobu 'ilayhi[one hundred times a day]",
	"RomanUrduTranslate":"Mein Allah se bakhshish mangta hun aur us ke huzoor tauba karta hun",
	"KannadaText": "ಅಸ್ತಗ್‍ಫಿರುಲ್ಲಾಹ ವಅತೂಬು ಇಲೈಹಿ (ಪ್ರತಿದಿನ ನೂರು ಸಲ)",
	"KannadaTranslate":"ನಾನು ಅಲ್ಲಾಹನೊಂದಿಗೆ ಪಾಪಮುಕ್ತಿ ಬೇಡುತ್ತಾ ಅವನೆಡೆಗೆ ಪಶ್ಚಾತ್ತಾಪಪಟ್ಟು ಮರಳುತ್ತಿದ್ದೇನೆ.",
	"Timing":"morning",
	"Repeat": 100,
	"Audio": "http://www.hisnmuslim.com/audio/ar/96.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ (ثلاثَ مرَّاتٍ إذا أمسى)",
	"EnglishText": "aAAoothu bikalimatil-lahit-tammati min sharri ma khalaq.",
	"EnglishTranslate": "I take refuge in Allah’s perfect words from the evil He has created.",
	"RomanUrduText": "aAAoothu bikalimatil-lahit-tammati min sharri ma khalaq.",
	"RomanUrduTranslate":"Mein Allah taala ke mukammal kalmaat ki panah mein aata hun us ki makhlooq ke shar se.",
	"KannadaText": "ಅಊದು ಬಿಕಲಿಮಾತಿಲ್ಲಾಹಿ ತ್ತಾಮ್ಮಾತಿ ಮಿನ್ ಶರ್ರಿ ಮಾ ಖಲಕ್ (ಸಂಜೆ ಮೂರು ಸಲ)",
	"KannadaTranslate":"ಅಲ್ಲಾಹನ ಪರಿಪೂರ್ಣ ವಚನಗಳೊಂದಿಗೆ ಅವನು ಸೃಷ್ಟಿಸಿದ ಕೆಡುಕಿನಿಂದ ನಾನು ರಕ್ಷೆ ಬೇಡುತ್ತಿದ್ದೇನೆ.",
	"Timing":"evening",
	"Repeat": 3,
	"Audio": "http://www.hisnmuslim.com/audio/ar/97.mp3"
	},
	{
	"Id": 1,
	"ArabicText": "اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبَيِّنَا مُحَمَّدٍ (عشرَ مرَّاتٍ)",
	"EnglishText": "Allaahumma salli wa sallim 'alaa Nabiyyinaa Muhammadin",
	"EnglishTranslate": "O Allaah, send prayers and peace upon our Prophet Muhammad.",
	"RomanUrduText": "Allaahumma salli wa sallim 'alaa Nabiyyinaa Muhammadin",
	"RomanUrduTranslate":"Ae Allah! rehmat nazil farma hamare Nabi Mohammad ﷺ par.",
	"KannadaText": "ಅಲ್ಲಾಹುಮ್ಮ ಸಲ್ಲಿ ವಸಲ್ಲಿಮ್ ಅಲಾ ನಬಿಯ್ಯಿನಾ ಮುಹಮ್ಮದ್ (ಹತ್ತು ಸಲ).",
	"KannadaTranslate":"ಓ ಅಲ್ಲಾಹು! ನಮ್ಮ ಪ್ರವಾದಿಯಾದ ಮುಹಮ್ಮದ್()ರವರ ಮೇಲೆ ಸಲಾತ್ ಮತ್ತು ಸಲಾಮ್ ಸುರಿಸು.",
	"Timing":"morningAndEvening",
	"Repeat": 10,
	"Audio": "http://www.hisnmuslim.com/audio/ar/98.mp3"
	}
	]]